# https://docs.github.com/en/actions

name: "Triage"

on: # yamllint disable-line rule:truthy
  # zizmor: ignore[dangerous-triggers] -- triage only adds labels via bot token.
  pull_request_target:
    types:
      - "opened"

permissions: {}

jobs:
  label:
    name: "Label"

    runs-on: "ubuntu-24.04"

    timeout-minutes: 5

    steps:
      - name: "Add labels based on branch name"
        uses: "ergebnis/.github/actions/github/pull-request/add-label-based-on-branch-name@07ba5718eac189644381e5972cd671c80c135ae7" # 1.13.4
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
