# https://docs.github.com/en/actions

name: "Triage"

on: # yamllint disable-line rule:truthy
  # zizmor: ignore[dangerous-triggers] -- triage only adds labels via bot token.
  pull_request_target:
    types:
      - "opened"

permissions: {}

jobs:
  label:
    name: "Label"

    runs-on: "ubuntu-latest"

    timeout-minutes: 5

    steps:
      - name: "Add labels based on branch name"
        uses: "ergebnis/.github/actions/github/pull-request/add-label-based-on-branch-name@fa753ba19f89b4923380b19dfcd80ad7eca4def9" # 1.13.0
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
